### ISSUE TITLE
Invalid source file for `a.pass.ts`

### ISSUE THREAD

**Issue by unional** [panuhorsmalahti/gulp-tslint#121]
gulp-tslint version: 7.1.0
tslint version: 5.2.0
Operating system: OSX

Example gulp configuration (if applicable):
With type-checking
```js
function positiveTest(config) {
  var program = tslint.Linter.createProgram('./tsconfig.json')
  return gulp.src(`spec/${config}/*.pass.ts`)
    .pipe(gulpTslint({
      configuration: `./${config}.js`,
      formatter: 'verbose',
      program
    }))
    .pipe(gulpTslint.report());
}
```

Error console output:
```sh
Error:
Invalid source file: align.pass.ts. Ensure that the files supplied to lint have a .ts, .tsx, .js or .jsx extension.

    at Linter.getSourceFile (/Users/hwong/github/unional/tslint-config-unional/node_modules/tslint/lib/linter.js:207:23)
    at Linter.lint (/Users/hwong/github/unional/tslint-config-unional/node_modules/tslint/lib/linter.js:74:31)
    at /Users/hwong/github/unional/tslint-config-unional/node_modules/gulp-tslint/index.js:102:16
```

**Comment by panuhorsmalahti** [comment]
Do you get the same error when running tslint manually?

**Comment by unional** [comment]
Nope.

**Comment by panuhorsmalahti** [comment]
You should update to gulp-tslint 8, then try if the error persists.

**Comment by ishitatsuyuki** [comment]
I have reproduced the case. The trick here is that if you tried to lint something that isn't covered by `tsconfig.json` globs, it result in undefined source, triggering the failure. For my case, it was node_modules, so adjusting the glob deliberately to exclude irrelevant files solved the error.

**Comment by sompylasar** [comment]
Refs https://github.com/palantir/tslint/issues/2208
