### ISSUE TITLE
TypeError: ruleConfiguration.forEach is not a function

### ISSUE THREAD

**Issue by FiniteLooper** [panuhorsmalahti/gulp-tslint#123]
gulp-tslint version: `8.0.0`
tslint version: `5.2.0`
Operating system: **Windows 10**

Example gulp configuration (if applicable):
```js
const gulp    = require("gulp");
const plumber = require("gulp-plumber");
const tsLint  = require("gulp-tslint");

gulp.task("do-stuff", ()=> {
    //Special task that just runs a single TSLint rule
    return gulp.src(["App/**/*.ts"])
        .pipe(plumber())
        .pipe(tsLint({
            configuration: {
                rules: {
                    "my-custom-rule-name": true
                }
            },
            formatter: "prose",
            rulesDirectory: "./my-rules-folder"
        }))
        .pipe(tsLint.report({ emitError: false }));
}
```
Error console output:
```
[09:54:39] Plumber found unhandled error:
 TypeError: ruleConfiguration.forEach is not a function
[09:54:39] Plumber found unhandled error:
 TypeError: ruleConfiguration.forEach is not a function
[09:54:39] Plumber found unhandled error:
 TypeError: ruleConfiguration.forEach is not a function
[09:54:39] Plumber found unhandled error:
 TypeError: ruleConfiguration.forEach is not a function
...
```

When I run a special gulp task with a custom configuration, I get the above errors.  A quick search online shows that others have gotten the same thing in other places.  This appears to be a change that TSLint made, and consumers of their API (like this project) need to make a small change.  I noticved this in the following issue threads:

* https://github.com/palantir/tslint/issues/2457
* https://github.com/wbuchwalter/tslint-loader/issues/73

**Comment by sujithklr93** [comment]
Peer dependencies - gulp-tslint
The tslint module is a peer dependency of gulp-tslint, which allows you to update tslint independently from gulp-tslint. gulp-tslint requires TypeScript version >=2 and tslint version >=4.

**Comment by panuhorsmalahti** [comment]
Yeah, what is the version of `typescript` you are using?

**Comment by vtabary** [comment]
Hi all,

I have the same problem here, with a bit more information : 

```
TypeError: ruleConfiguration.forEach is not a function
    at Object.convertRuleOptions (/project/node_modules/tslint/lib/configuration.js:426:23)
    at Linter.getEnabledRules (/project/node_modules/tslint/lib/linter.js:187:47)
    at Linter.lint (/project/node_modules/tslint/lib/linter.js:74:33)
    at /project/node_modules/gulp-tslint/index.js:105:16
    at wrappedMapper (/project/node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (/project/node_modules/map-stream/index.js:95:21)
    at DestroyableTransform.ondata (/project/node_modules/readable-stream/lib/_stream_readable.js:541:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:191:7)
    at readableAddChunk (/project/node_modules/readable-stream/lib/_stream_readable.js:212:18)
```

I checked the same configuration by using the tslint cli, and everything is ok (no linting error).

And I trier with an empty configuration file, got the same error if I leave the "rules" key. If the configuration file is equal to "{}", I got : 

```
TypeError: Cannot read property 'forEach' of undefined
    at Object.convertRuleOptions (/project/node_modules/tslint/lib/configuration.js:426:22)
    at Linter.getEnabledRules (/project/node_modules/tslint/lib/linter.js:187:47)
    at Linter.lint (/project/node_modules/tslint/lib/linter.js:74:33)
    at /project/node_modules/gulp-tslint/index.js:105:16
    at wrappedMapper (/project/node_modules/map-stream/index.js:83:19)
    at Stream.stream.write (/project/node_modules/map-stream/index.js:95:21)
    at DestroyableTransform.ondata (/project/node_modules/readable-stream/lib/_stream_readable.js:541:20)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:191:7)
    at readableAddChunk (/project/node_modules/readable-stream/lib/_stream_readable.js:212:18)
```

typescript : 2.3.4
tslint : 5.4.0
gulp-tslint : 8.1.0

**Comment by thomas-darling** [comment]
Same problem here...

**Comment by ex37** [comment]
Can confirm that getting `TypeError: ruleConfiguration.forEach is not a function` error on the following package versions:

tslint : 5.4.3
gulp-tslint : 8.1.1
typescript: 2.2.2

**Comment by bhargav-sae** [comment]
```
TypeError: ruleConfiguration.forEach is not a function
```
*tslint*: 5.4.3
*gulp-tslint*: 8.1.1
*typescript*: 2.2.2

**Comment by kolupaevri** [comment]
Same error:
```
TypeError: ruleConfiguration.forEach is not a function
    at Object.convertRuleOptions (C:\Developing\SDL UI\controls\node_modules\tslint\lib\configuration.js:426:23)
    at Linter.getEnabledRules (C:\Developing\SDL UI\controls\node_modules\tslint\lib\linter.js:187:47)
    at Linter.lint (C:\Developing\SDL UI\controls\node_modules\tslint\lib\linter.js:74:33)
    at C:\Developing\SDL UI\controls\node_modules\gulp-tslint\index.js:103:16
    at wrappedMapper (C:\Developing\SDL UI\controls\node_modules\gulp-tslint\node_modules\map-stream\index.js:83:19)
    ...
```
**tslint**: 5.4.3
**gulp-tslint**: 8.1.1
**typescript**: 2.4.0

**Comment by SteffenAnders** [comment]
any solutions here?

**Comment by mgroenhoff** [comment]
The configuration parameter to gulp-tslint can be of type string (a path to a tslint.json file) or an object of type [`IConfigurationFile`](https://github.com/palantir/tslint/blob/master/src/configuration.ts#L26). The `rules` property of the `IConfigurationFile` is of type `Map<string, Partial<IOptions>>` and cannot be assigned an object literal (hence it can not find the `.forEach` method).

**Comment by ocombe** [comment]
Thanks @mgroenhoff, switching from a simple require of the file to passing the path to the configuration option fixed the issue for me

**Comment by Izhaki** [comment]
Possibly, only possibly, [this comment](https://github.com/palantir/tslint/issues/2457#issuecomment-332822605) will guide the solution.

Actually, pretty sure it will.

**Comment by orellabac** [comment]
I dit something like:
gulp.task('tslint', function() {
    const tslint = require('tslint');
    const rawConfig = tslint.Configuration.EMPTY_CONFIG;
    rawConfig.rules = {
        semicolon: [true, 'always'],
      };
    const config = tslint.Configuration.parseConfigFile(rawConfig); 
    const options = {
        fix: false,
        configuration: config
      };

    return gulp.src('src/**/*.ts')
      .pipe(gtslint(options))
      .pipe(gtslint.report());
  });
