### ISSUE TITLE
semicolonRule - TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jerryorta-dev** [panuhorsmalahti/gulp-tslint#50]
I'm receiving the following error stack:

I have a "fix" for which I'm submitting a PR. I'm not sure if it's a legit fix, but submitting to illustrate what is removing the error, yet detecting missing semicolons in linted files.

```bash

/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/rules/semicolonRule.js:70
        for (var _i = 0, _a = node.members; _i < _a.length; _i++) {
                                                   ^

TypeError: Cannot read property 'length' of undefined
    at SemicolonWalker.visitInterfaceDeclaration (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/rules/semicolonRule.js:70:52)
    at SemicolonWalker.SyntaxWalker.visitNode (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/language/walker/syntaxWalker.js:332:22)
    at /Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/language/walker/syntaxWalker.js:443:63
    at visitEachNode (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/node_modules/typescript/lib/typescript.js:6886:30)
    at Object.forEachChild (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/node_modules/typescript/lib/typescript.js:7043:24)
    at SemicolonWalker.SyntaxWalker.walkChildren (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/language/walker/syntaxWalker.js:443:12)
    at SemicolonWalker.SyntaxWalker.visitNode (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/language/walker/syntaxWalker.js:437:22)
    at SemicolonWalker.SyntaxWalker.walk (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/language/walker/syntaxWalker.js:6:14)
    at Rule.AbstractRule.applyWithWalker (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/language/rule/abstractRule.js:18:16)
    at Rule.apply (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/rules/semicolonRule.js:14:21)
    at Linter.lint (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/tslint/lib/tslint.js:26:41)
    at /Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/gulp-tslint/index.js:95:34
    at respond (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/gulp-tslint/node_modules/rcloader/index.js:68:7)
    at respond (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/rcfinder/index.js:140:7)
    at next (/Users/jerryorta-dev/Dev/UIUXEngineering/angular1-typescript-ES6-jspm-gulp/node_modules/rcfinder/index.js:167:16)
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickDomainCallback (node.js:426:13)
```

**Comment by jerryorta-dev** [comment]
Sorry, submitted this issue to the wrong project.
